### create new order
POST http://localhost:4000/api/v1/orders/new
Content-Type: application/json

{
  "shippingInfo": {
    "address": "123 Main Street",
    "city": "New York",
    "phoneNo": "123-456-7890",
    "zipCode": "10001",
    "country": "USA"
  },
  "orderItems": [
    {
      "name": "CAN USB FD Adapter (GC-CAN-USB-FD) 2",
      "quantity": 2,
      "image": "http://res.cloudinary.com/udemy-courses/image/upload/v1689961785/shopit/products/demo/b9m0ddogmkd8xnypmh1l.jpg",
      "price": "39.99",
      "product": "650be7eadbcd491deb81e544"
    }
  ],
  "paymentMethod": "COD",
  "paymentInfo": {
    "id": "payment_id_here",
    "status": "Not Paid"
  },
  "itemsPrice": 79.97,
  "taxAmount": 7.99,
  "shippingAmount": 5.99,
  "totalAmount": 93.95
}

### get order details
GET http://localhost:4000/api/v1/orders/66da470b61f817641fd34da8

### get current user orders
GET http://localhost:4000/api/v1/me/orders