### get all products
GET http://localhost:4000/api/v1/products

### create new product
POST http://localhost:4000/api/v1/admin/products
Content-Type: application/json

{
  
  "description": "Ultra-fast cards (2) to take better pictures and Full HD videos (1) with your compact to mid-range point-and-shoot cameras and camcorders. With SanDisk Ultra SDXC UHS-I cards you’ll benefit from faster downloads, high capacity, and better performance to capture and store 128GB (5) of high quality pictures and Full HD video (1). Take advantage of ultra-fast read speeds of up to 80MB/s (3) to save time moving photos and videos from the card to your computer. From a leader in flash memory storage, SanDisk Ultra SDXC UHS-I cards are compatible with SDHC and SDXC digital devices, and come with a 10-year limited warranty (6).",
  "ratings": 4.5,
  "images": [
    
  ],
  "category": "Electronics",
  "seller": "Ebay",
  "stock": 50,
  "numOfReviews": 32
}

###"price": 45.89,
###"name": "SanDisk Ultra 128GB SDXC UHS-I Memory Card up to 80MB/s",

### get product details
GET http://localhost:4000/api/v1/products/66d89d4364489cec7710219e

### update product details
PUT http://localhost:4000/api/v1/products/66d89d4364489cec7710219e
Content-Type: application/json

{
  "name": "SanDisk Ultra 128GB SDXC UHS-I Memory Card up to 100MB/s"
}

### delete product
DELETE http://localhost:4000/api/v1/products/66d89d4364489cec7710219e
